apiVersion: v1
kind: Service
metadata:
  labels:
    label-key: spa-deployment 
  name: spa-demo-service-name
spec:
  type: NodePort #ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http #newly added
  selector:
    label-key: spa-deployment
