apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      label-key: nginx-deployment
  template:
    metadata:
      labels:
        label-key : nginx-deployment
    spec:
      containers:
        - name: nginx-angular-display
          image: danielbautz317/spa-demo:v1
          imagePullPolicy: Always
          ports:
        #  - containerPort: 80
          - name: http
            containerPort: 80
            #hostPort for usage of a static port to access the webserver
            hostPort: 31007
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
