apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      label-key: spa-deployment
  template:
    metadata:
      labels:
        label-key : spa-deployment
    spec:
      containers:
        - name: spa-demo-container
          image: danielbautz317/spa-demo:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 80