apiVersion: v1
kind: Service
metadata:
  labels:
    label-key: spa-deployment
  name: spa-demo-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    label-key: spa-deployment
