apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        label-key : label-value  
    spec:
      selector:
        matchLabels:
          app: spa-deployment
      template:
        metadata:
          labels:
            app: spa-deployment
        spec:
          containers:
            - name: spa-demo-container
              image: danielbautz317/spa-demo:v1
              imagePullPolicy: Always
              ports:
              - containerPort: 80